import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MenuTab from "./components/MenuTab/MenuTab";
import "./globals.css";
import styles from "./layout.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles["background-1"]}>
          <div className={styles["background-2"]}>
            <header className={styles.header}>
              <div className={styles.users}>
                <p>TODAY 1 | TOTAL 2025</p>
              </div>
              <div className={styles["top-message"]}>
                <p>내가 최고짱이다~~</p>
              </div>
            </header>
            <div className={styles["children-wrapper"]}>
              {children}
              <MenuTab />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
